### ISSUE TITLE
Add support for watchlist page

### ISSUE THREAD

**Issue by iamkroot** [Luffier/the-pirate-calendar#2]
First off, thanks for this script! Very useful, will save me some keypresses :)

I generally use my watchlist as the start point for searches. Would it be possible to add the button to all the items on a list page?

**Comment by iamkroot** [comment]
Looking at the source code, looks like the script assumes all items are shows (or movies) and can't handle mixed types. To support this, we'd need to extract the type for each item from its url (trakt.tv/show and trakt.tv/movie).

**Comment by Luffier** [comment]
Done! Hope you like it!

Lists have a different layout than other pages, and there's no room for the link at some resolutions, so the icons need to be squeezed. I added some alternatives in the settings menu in case people find it ugly.
